"""create reply_records table

Revision ID: 0ce53af38a4f
Revises:
Create Date: 2026-02-09 16:05:01.325272

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0ce53af38a4f"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reply_records",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("author_name", sa.Text(), nullable=True),
        sa.Column("author_profile_url", sa.Text(), nullable=True),
        sa.Column("post_url", sa.Text(), nullable=True),
        sa.Column("post_text", sa.Text(), nullable=False),
        sa.Column("article_text", sa.Text(), nullable=True),
        sa.Column("image_ref", sa.Text(), nullable=True),
        sa.Column("preset_id", sa.Text(), nullable=False),
        sa.Column("prompt_text", sa.Text(), nullable=False),
        sa.Column("generated_reply", sa.Text(), nullable=True),
        sa.Column("final_reply", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("created_date", sa.DateTime(), nullable=False),
        sa.Column("generated_at", sa.DateTime(), nullable=True),
        sa.Column("approved_at", sa.DateTime(), nullable=True),
        sa.Column("llm_model_identifier", sa.Text(), nullable=True),
        sa.Column("llm_request_id", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("reply_records")
    # ### end Alembic commands ###
